PREFIX mag: <http://ex.org/car-crashes#>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX ex: <http://example.org/a#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# All crashes by year: car and bicycle
SELECT *
WHERE
{
  {
    SELECT
      ?year
      (COUNT(?year) AS ?nbCrashes)
    WHERE
    {
      ?s a mag:Crash ;
        dbo:year ?year
    }
    GROUP BY ?year
  }

  {
    SELECT
      ?year
      (COUNT(?year) AS ?nbBikeCrashes)
    WHERE
    {
      ?URI rdf:type ex:AccidentsVelo;
        ex:date ?Date;
      
      BIND(YEAR(xsd:date(?Date)) as ?year)
    }
    GROUP BY ?year
  }
}
