# Formatted date and city of the last 10 crashes
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX exif: <http://www.w3.org/2003/12/exif/ns#>
PREFIX mag: <http://ex.org/car-crashes#>
PREFIX dbo: <http://dbpedia.org/ontology/>

SELECT
  ?year
  (COUNT(?year) AS ?nbCrashes)
WHERE
{
  ?s a mag:Crash ;
    dbo:year ?year
}
GROUP BY ?year